### ISSUE TITLE
按照教程做了一遍出现一个错误

### ISSUE THREAD

**Issue by izenloading** [pantsPoi/Spruche#6]
module.js:472
    throw err;
    ^

Error: Cannot find module '../gt-sdk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/test/Documents/rn/Spruche/routes/index.js:3:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spruche@0.0.6 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spruche@0.0.6 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spruche package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spruche
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spruche
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by IceEnd** [comment]
你这个版本有点老，之前0.0.6提交代码删掉多余模块的忘记去掉引用，我刚刚看了一下master 0.0.7的代码是正确的，你重新下一次master吧。

**Comment by izenloading** [comment]
我好想是在oschina下的006版本，你那边没有更新。现在更新到新版本就可以了
